import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import tw from "tailwind-styled-components"
import axios from 'axios'
import { useState ,useEffect } from 'react'
import Link from 'next/link'
export default function Home() {

  const [data, setData] = useState([])
useEffect(() => {

fetchposts()

}, [])


const fetchposts = async () => {

  const res = await axios.get('http://localhost:1337/api/posts')
 


  try {
   
    const json = await res.data.data

    setData(json);
    console.log('json---->', json)


  } catch (error) {
   console.log('error', error)
  }







}


  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

   
<div className= ' text-2xl text-center '>
  next starpi app


<div>
  {data.map((item, index) => {
    return (
      <div key='item.id' className =' my-4 text-2xl font-bold'>
        <h1>
          <Link href={`/${item.id}`}>
          {item.attributes.title}
          </Link>

          
        </h1>
      </div>
    )})}
</div>


</div>


    </div>
  )
}


