import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import tw from "tailwind-styled-components"
import axios from 'axios'
import { useState ,useEffect } from 'react'
import Link from 'next/link'
import { useQuery, gql } from '@apollo/client'
import { getPosts } from '../services'
import {getCompaniesSlugs , getCompanyBySlug } from '../dataLayer/strapi/company'
import {getJobsSlugs , getJobBySlug , getJobsByCompanyId } from '../dataLayer/strapi/job'



export default function Home({posts}) {

  const [data, setData] = useState([])

console.log('posts',posts)


useEffect(() => {
  getJobsByCompanyId(2).then(data => {
    console.log('data-----------> jobs',data)
    setData(data)
  }).catch(err => {
    console.log(err)
  }).finally(() => {
    console.log('finally')
  } )
} ,[])



  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

   
<div className= ' text-2xl text-center '>
  next starpi app

{/* 
<div>
  {data.map((item, index) => {
    return (
      <div key='item.id' className =' my-4 text-2xl font-bold'>
        <h1>
          <Link href={`/${item.id}`}>
          {item.attributes.title}
          </Link>

          
        </h1>
      </div>
    )})}
</div> */}


<div>

</div>

</div>


    </div>
  )
}



export async function getStaticProps() {
  const posts = (await getPosts()) || [];

  return{
    props: {posts}
  }
}

